server:
  port: 8080

openAI:
  apiKey: ""

database:
  enabled: false
  host: "localhost"
  port: 5432
  user: "admin"
  password: "admin"

migration:
  enabled: false
  path: "scripts/dbmigrations"
