name: Test Coverage Check

on: [ push, pull_request ]

jobs:
  test_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build and test
        run: make test

      - name: Check test coverage
        run: |
          COVERAGE_THRESHOLD=10  # 设置测试覆盖率的阈值
          CURRENT_COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | tr -d '%')
          if (( $CURRENT_COVERAGE < $COVERAGE_THRESHOLD )); then
            echo "Test coverage is below the threshold ($CURRENT_COVERAGE% < $COVERAGE_THRESHOLD%)"
            exit 1
          else
            echo "Test coverage meets the threshold ($CURRENT_COVERAGE% >= $COVERAGE_THRESHOLD%)"
          fi
