name: Test Coverage Check

on:
  workflow_run:
    workflows: ["Lint Test Checker"]
    branches: [ "master" ]
    types:
      - completed

jobs:
  test_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build and test
        run: make test

      - name: Check test coverage
        run: |
          make check-coverage
