name: Integration Test

on:
  workflow_run:
    workflows: [ "Lint Test Checker" ]
    branches: [ "master" ]
    types:
      - completed

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Integration test
      run: make integration-test
